#ifndef __PIN_CONFIGURATION_H__
#define __PIN_CONFIGURATION_H__

/*********** HC-05 ***********/
#define HC05_SYSCTL_PERIPH_UARTx SYSCTL_PERIPH_UART4 // Clock for UART
#define HC05_SYSCTL_PERIPH_GPIOx SYSCTL_PERIPH_GPIOK // Clock for Tx, Rx GPIO
#define HC05_UART_BASE UART4_BASE

#define HC05_UART_RX_GPIO_PORT_BASE GPIO_PORTK_BASE
#define HC05_UART_RX_GPIO_PIN GPIO_PIN_0
#define HC05_UART_RX_GPIO_AF GPIO_PK0_U4RX

#define HC05_UART_TX_GPIO_PORT_BASE GPIO_PORTK_BASE
#define HC05_UART_TX_GPIO_PIN GPIO_PIN_1
#define HC05_UART_TX_GPIO_AF GPIO_PK1_U4TX

#define HC05_EN_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOL
#define HC05_EN_PORT_BASE GPIO_PORTL_BASE
#define HC05_EN_PIN GPIO_PIN_5

#define HC05_STATE_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOA
#define HC05_STATE_PORT_BASE GPIO_PORTA_BASE
#define HC05_STATE_PIN GPIO_PIN_4

/*********** BUTTON ***********/
#define BUTTON_BTN0_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOA
#define BUTTON_BTN0_PORT_BASE GPIO_PORTA_BASE
#define BUTTON_BTN0_PIN GPIO_PIN_6

#define BUTTON_BTN1_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOM
#define BUTTON_BTN1_PORT_BASE GPIO_PORTM_BASE
#define BUTTON_BTN1_PIN GPIO_PIN_4

#define BUTTON_BTN2_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOM
#define BUTTON_BTN2_PORT_BASE GPIO_PORTM_BASE
#define BUTTON_BTN2_PIN GPIO_PIN_5

/*********** AD8302 ***********/
#define VMAG ADC_Channel_8
#define VMAG_ADC_SYSCTL_PERIPH SYSCTL_PERIPH_ADC0
#define VMAG_ADC_AIN_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOE
#define VMAG_ADC_BASE ADC0_BASE
#define VMAG_ADC_CHANNEL ADC_CTL_CH2
#define VMAG_AIN_PORT_BASE GPIO_PORTE_BASE
#define VMAG_AIN_PIN GPIO_PIN_0

#define VPHS ADC_Channel_9
#define VPHS_ADC_SYSCTL_PERIPH SYSCTL_PERIPH_ADC1
#define VPHS_ADC_AIN_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOE
#define VPHS_ADC_BASE ADC1_BASE
#define VPHS_ADC_CHANNEL ADC_CTL_CH3
#define VPHS_AIN_PORT_BASE GPIO_PORTE_BASE
#define VPHS_AIN_PIN GPIO_PIN_1

/*********** LCD ***********/
// RST - PA5
#define LCD_RST_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOA
#define LCD_RST_PORT GPIO_PORTA_BASE
#define LCD_RST_PIN GPIO_PIN_5

// CE - PE0
#define LCD_CE_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOE
#define LCD_CE_PORT GPIO_PORTE_BASE
#define LCD_CE_PIN GPIO_PIN_0

// DC - PE1
#define LCD_DC_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOE
#define LCD_DC_PORT GPIO_PORTE_BASE
#define LCD_DC_PIN GPIO_PIN_1

// DIN - PE2
#define LCD_DIN_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOE
#define LCD_DIN_PORT GPIO_PORTE_BASE
#define LCD_DIN_PIN GPIO_PIN_2

// CLK - PE3
#define LCD_CLK_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOE
#define LCD_CLK_PORT GPIO_PORTE_BASE
#define LCD_CLK_PIN GPIO_PIN_3

// LIGHT - PD5
#define LCD_LIGHT_SYSCTL_PERIPH SYSCTL_PERIPH_GPIOD
#define LCD_LIGHT_PORT GPIO_PORTD_BASE
#define LCD_LIGHT_PIN GPIO_PIN_5

/*********** ADF4351 ***********/
#define ADF_SYSCTL_PERIPH_GPIOx SYSCTL_PERIPH_GPIOD
#define ADF_GPIO_PORT_BASE GPIO_PORTD_BASE
#define ADF_CE_PIN GPIO_PIN_6
#define ADF_LE_PIN GPIO_PIN_3
#define ADF_CLK_PIN GPIO_PIN_1
#define ADF_MUX_PIN GPIO_PIN_0
#define ADF_DAT_PIN GPIO_PIN_2

/*********** LED ***********/
#define LED1_BUILTIN_PERIPHERAL SYSCTL_PERIPH_GPION
#define LED1_BUILTIN_PORT GPIO_PORTN_BASE
#define LED1_BUILTIN_PIN GPIO_PIN_1

#define LED2_BUILTIN_PERIPHERAL SYSCTL_PERIPH_GPION
#define LED2_BUILTIN_PORT GPIO_PORTN_BASE
#define LED2_BUILTIN_PIN GPIO_PIN_0

#define LED3_BUILTIN_PERIPHERAL SYSCTL_PERIPH_GPIOF
#define LED3_BUILTIN_PORT GPIO_PORTF_BASE
#define LED3_BUILTIN_PIN GPIO_PIN_4

#define LED4_BUILTIN_PERIPHERAL SYSCTL_PERIPH_GPIOF
#define LED4_BUILTIN_PORT GPIO_PORTF_BASE
#define LED4_BUILTIN_PIN GPIO_PIN_0

#endif /* __PIN_CONFIGURATION_H__ */
